# =============================================================
# app/schemas/context.py — Request & Response Models for /context (v2)
#
# WHAT CHANGED IN v2:
#   - Added `extracted_topic` field (shows what topic was actually searched)
#   - Added `historical_summary` field (1-sentence concise overview)
#   - Added `geopolitical_relevance` field (detected from Wikipedia content)
#   - Increased `related_topics` max from 6 to 8
# =============================================================

from pydantic import BaseModel, Field
from typing import Optional, List


# =============================================================
# NESTED SCHEMAS
# =============================================================

class TimelinePoint(BaseModel):
    """A single point on the historical timeline."""
    year:  str = Field(description="Year or decade (e.g. '2009', '1990').")
    event: str = Field(description="One-sentence factual description from Wikipedia.")


class ContextSource(BaseModel):
    """A real news article used as a reference source (from NewsAPI)."""
    title:        str           = Field(description="Article headline.")
    url:          str           = Field(description="Direct link to the article.")
    source_name:  str           = Field(description="Publisher name, e.g. 'BBC News'.")
    published_at: Optional[str] = Field(
        default=None,
        description="ISO 8601 publication timestamp."
    )


# =============================================================
# MAIN RESPONSE SCHEMA
# =============================================================

class ContextResponse(BaseModel):
    """
    Full historical context response returned by GET /context.

    All text fields contain only factual data from Wikipedia and NewsAPI.
    No AI-generated or hallucinated content.
    """

    topic: str = Field(
        description="The original topic that was searched (echoed from query param)."
    )

    extracted_topic: Optional[str] = Field(
        default=None,
        description=(
            "The intelligently extracted topic used for Wikipedia lookup. "
            "e.g. 'Trump warns Iran' → 'Iran United States relations'."
        )
    )

    historical_context: str = Field(
        description=(
            "A factual 3-sentence introductory paragraph about this topic, "
            "sourced directly from Wikipedia's summary API."
        )
    )

    historical_summary: Optional[str] = Field(
        default=None,
        description=(
            "A single-sentence concise summary of what this topic is. "
            "Derived from Wikipedia's description field or first sentence."
        )
    )

    timeline_points: List[TimelinePoint] = Field(
        default_factory=list,
        description=(
            "Chronological key historical moments extracted from Wikipedia. "
            "Includes year references and decade references."
        )
    )

    key_events: List[str] = Field(
        default_factory=list,
        description="3–5 significant factual sentences from Wikipedia."
    )

    why_it_matters: str = Field(
        description=(
            "A paragraph explaining the topic's global, economic, or social relevance. "
            "Extracted from Wikipedia — not generated by AI."
        )
    )

    geopolitical_relevance: Optional[str] = Field(
        default=None,
        description=(
            "A sentence describing the geopolitical or economic significance "
            "of this topic, if applicable. Empty string if not relevant."
        )
    )

    related_topics: List[str] = Field(
        default_factory=list,
        description="Related subject areas or subtopics found via Wikipedia (up to 8)."
    )

    sources: List[ContextSource] = Field(
        default_factory=list,
        description=(
            "Real news articles from NewsAPI related to this topic. "
            "Live published references, not fabricated."
        )
    )

    wikipedia_url: Optional[str] = Field(
        default=None,
        description="Direct link to the Wikipedia page used as the primary source."
    )

    data_freshness: str = Field(
        description="UTC timestamp when this context response was assembled."
    )
